#use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

target 'Alister-Example' do
    pod 'libextobjc'
#  pod 'Alister', :path => '../'
  pod 'Masonry'
  pod 'Reveal-iOS-SDK', '~> 1.6.1', :configurations => ['Debug']
#  pod 'Octopus', :git => 'ssh://git@stash.anoda.mobi:7999/anios/ios-octopus.git', :branch => '0.1.0', :commit => '1126bfc'

end

target 'Alister-Example-Tests' do
    pod 'Expecta'
    pod 'Specta'
#    pod 'Alister', :path => '../'
    pod 'OCMock'
end


target 'Alister-Tests' do
    pod 'Expecta'
    pod 'Specta'
    pod 'OCMock'
end
