#use_frameworks!

target 'Alister-Example' do
  pod 'Alister', :path => '../'
  pod 'Masonry'
  pod 'Reveal-SDK', :configurations => ['Debug']
end

target 'Alister-Example-Tests' do
    pod 'Expecta'
    pod 'Specta'
    pod 'Alister', :path => '../'
    pod 'OCMock'
end

