
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "DEBUG")
    slather(
      cobertura_xml: true,
      output_directory: "test_output",
      proj: "Alister-Example.xcodeproj",
      workspace: "Alister-Example.xcworkspace",
      scheme: "DEBUG",
      ignore:['../../*', 
      'Pods/*', 
      '*/Vendor/*', 
      '*/Application/BundleFiles/*',
      '*/Controllers/Debug/DebugVC/*'])
  end

#  lane :acceptance_tests do
#    scan(scheme: "DEBUG_ACCEPTANCE")
#  end


  after_all do |lane|
    # This block is called, only if the executed lane was successful 
    slack(
      use_webhook_configured_username_and_icon: true,
      message: "Fastlane was successful :rocket:",
      success: true,
      default_payloads: [:lane, :test_result, :git_branch, :git_author],
    )
  end


  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
