#use_frameworks!
#install! 'cocoapods', :deterministic_uuids => false

target 'Alister-Tests' do
    pod 'Expecta'
    pod 'Specta', :git => 'https://github.com/specta/specta.git', :commit => '18952b7'
    pod 'OCMock'
end
